//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GII.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Countries = new HashSet<Country>();
            this.Places = new HashSet<Place>();
            this.Segments = new HashSet<Segment>();
            this.Segments1 = new HashSet<Segment>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual ICollection<Segment> Segments1 { get; set; }
    }
}
