//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GII.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
    }
}
