//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GII.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int SegmentId { get; set; }
        public int OriginCityId { get; set; }
        public int DestinationCityId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public Nullable<int> NextSegmentId { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Segment Segment1 { get; set; }
        public virtual Segment Segment2 { get; set; }
    }
}
